- name: some fun managing a web service with ansible
  hosts: all

  pre_tasks:
    - name: making sure virtualenv is installed
      apt: pkg=python-virtualenv
      sudo: yes

  vars:
    port: 8080

  roles:
    - role: eggsby.supervise
      name: web-server
      command: python -m SimpleHTTPServer {{ port }}
      directory: ~/public/web
